name: corona_karma
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.25
  location: ^2.5.0
  timeago: ^2.0.26
  flutter_svg: ^0.17.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.4+3
  firebase_database: ^3.1.3
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  provider: ^4.0.4

flutter:
  assets:
    - assets/profile.png
    - assets/chatIcons/dog.svg
    - assets/chatIcons/groceries.svg
    - assets/chatIcons/pills.svg
    - assets/chatIcons/postal.svg
    - assets/tabIcons/chat.svg
    - assets/tabIcons/map.svg
    - assets/tabIcons/profile.svg
    - assets/tabIcons/chat_active.svg
    - assets/tabIcons/map_active.svg
    - assets/tabIcons/profile_active.svg
    - assets/maps_position.svg
    - assets/shelfIcons/shelf.svg
    - assets/shelfIcons/shelf_beam.svg
    - assets/shelfIcons/toilet_roll.svg
    - assets/shelfIcons/cereal.svg
    - assets/shelfIcons/bleach.svg
    - assets/shelfIcons/pasta.svg